name: Lint commits

on:
  pull_request:

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: Install commitlint
        run: npm install -D @commitlint/cli @commitlint/config-conventional conventional-changelog-conventionalcommits

      - name: Validate commit
        run: npx commitlint --last --verbose
